### ISSUE TITLE
代码错误汇报

### ISSUE THREAD

**Issue by SwordArt0820** [git-flyer/Red_black_tree#1]
您好，我是一名大学生，在使用您的代码的时候我发现自己手构大样例怎么也过不去，所以仔细的阅读了您的代码。
您的代码中共有2处严重错误，一个是leftrotate和rightrotate中，您没有对current->right->left和current->left->right设置父节点：
另一个就是在detele的goto中，应将label1和label2移入if语句中，否则由于left和right没有重新计算代码会出现错误，您可以写一个简易的红黑树check程序（check黑节点个数相同和判定x->left->parent == x &&x->right->parent == x）

**Comment by git-flyer** [comment]
感谢帮忙debug，很荣幸能帮助到您，最近在忙一些别的事，抽空review(๑•̀ㅂ•́)
